name: Daily Calorie Summary
on:
  schedule:
    - cron: '59 20 * * *'  # 23:59 EET
  workflow_dispatch:
jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install notion-client
    - run: python daily-summary.py
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DAILY_SUM_ARCHIVE_DB: ${{ secrets.DAILY_SUM_ARCHIVE_DB }}
